#!/bin/sh
# Build kipy (kicad-python) master against the v11 nightly protos and wire
# it into the repo .venv WITHOUT pip's wheel build (which needs protoc-gen-mypy
# matching a newer protobuf runtime than ours, and drops kipy/proto/schematic
# from the wheel because its __init__.py is not git-tracked).
#
# What this does instead:
#   1. clone kicad-python + kicad api submodule into .tools/kicad-python
#   2. generate *_pb2.py in-tree: protoc (no --mypy_out) + protol import fixup
#   3. write kipy/kicad_api_version.py (normally done by their build hook)
#   4. point the venv at the tree via a .pth file (manual editable install)
#
# Needs: protoc on PATH matching the venv protobuf runtime major
#        (runtime 5.29.x -> protoc 29.x; official zip into ~/.local works),
#        and `pip install mypy-protobuf protoletariat` in the venv (protol).
set -e

REPO="$(dirname "$(dirname "$(readlink -f "$0")")")"
TREE="$REPO/.tools/kicad-python"
VENV="$REPO/.venv"
export VENV  # the embedded python below reads it

[ -d "$TREE" ] || git clone --depth 1 --recursive \
    https://gitlab.com/kicad/code/kicad-python.git "$TREE"

cd "$TREE"
"$VENV/bin/python" - <<'EOF'
import os, pathlib, subprocess
os.environ["PATH"] = os.path.expanduser("~/.local/bin") + ":" + os.environ["PATH"]
root = pathlib.Path.cwd()
pin, pout = root / "kicad/api/proto", root / "kipy/proto"
protos = [str(p) for p in pin.rglob("*.proto")]
venv = pathlib.Path(os.environ["VENV"]) / "bin"
subprocess.run(["protoc", f"--python_out={pout}", f"--proto_path={pin}",
                "--experimental_allow_proto3_optional", *protos], check=True)
subprocess.run([str(venv / "protol"), "--dont-create-package", "--in-place",
                "--exclude-google-imports", "--python-out", str(pout),
                "protoc", "--experimental_allow_proto3_optional",
                "--proto-path", str(pin), *protos], check=True)
for d in pout.rglob("**/"):
    (d / "__init__.py").touch(exist_ok=True)
desc = subprocess.run(["git", "describe", "--long", "--always"],
                      cwd=root / "kicad", capture_output=True, text=True
                      ).stdout.strip() or "unknown"
(root / "kipy/kicad_api_version.py").write_text(
    "# This file is automatically generated, do not modify it\n"
    f'KICAD_API_VERSION = "{desc}"\n')
print("protos generated, api version:", desc)
EOF

"$VENV/bin/pip" uninstall -q -y kicad-python 2>/dev/null || true
SITE="$("$VENV/bin/python" -c 'import site; print(site.getsitepackages()[0])')"
echo "$TREE" > "$SITE/kicad_python_dev.pth"
"$VENV/bin/python" -c "
import kipy
from kipy.proto.schematic import schematic_types_pb2
from kipy import KiCad
assert hasattr(KiCad, 'get_schematic')
print('kipy master OK:', kipy.__file__)"
